name: 'Test Build'

on:
  workflow_dispatch:
  push:
    branches: 
      - dev
  pull_request:

permissions:
  contents: read
  pull-requests: read

jobs:
  linux-ubuntu_build:
    runs-on: "ubuntu-latest"
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v4

      - name: 'Install Build Dependencies'
        run: .github/workflows/buildtest/debian/install_dep.sh

      - name: 'Test the Build'
        run: 'make -j$(nproc) all'
